services:
  huh.filename_sanitizer.data_container.settings:
    class: HeimrichHannot\FilenameSanitizerBundle\DataContainer\Settings
    public: true
    autowire: true
  huh.filename_sanitizer.event_listener.hook_listener:
    class: HeimrichHannot\FilenameSanitizerBundle\EventListener\HookListener
    public: true
    autowire: true